apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      restartPolicy: Always
      containers:
      - image: 123497/exchange-service:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: exchange-service
        ports:
          - containerPort: 8000
        env:
          - name: DB_HOST
            value: mysqldb
          - name: DB_NAME
            value: db-exchange-service
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            value: Password123
      