apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    name: mysql-service
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      nodePort: 30036
      targetPort: 3306
  selector:
    app: mysqldb